---
deployment:
  tasks:
    - export DEPLOYPATH=/home/generaltiniogov/public_html/test/
    - /bin/cp -R generaltinio.gov.ph/App $DEPLOYPATH
    - /bin/cp -R generaltinio.gov.ph/assets $DEPLOYPATH
    - /bin/cp -R generaltinio.gov.ph/uploads $DEPLOYPATH
    - /bin/cp -R generaltinio.gov.ph/vendor $DEPLOYPATH
    - /bin/cp generaltinio.gov.ph/.env.example $DEPLOYPATH
    - /bin/cp generaltinio.gov.ph/.htaccess $DEPLOYPATH
    - /bin/cp generaltinio.gov.ph/composer.json $DEPLOYPATH
    - /bin/cp generaltinio.gov.ph/composer.lock $DEPLOYPATH
    - /bin/cp generaltinio.gov.ph/index.php $DEPLOYPATH
    - /bin/cp generaltinio.gov.ph/routes.php $DEPLOYPATH
