<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" sizes="any" href="/monitoring-system/assets/images/icon.svg" type="image/svg+xml" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
    <title>Monitoring System</title>
    <script type="text/javascript" src="/monitoring-system/assets/config.js"></script>
    <style>
      html {
        overflow: hidden;
      }

      * {
        -webkit-print-color-adjust: exact !important;
        print-color-adjust: exact !important;
      }
    </style>
    <script type="module" crossorigin src="/monitoring-system/assets/index-y7WR9qmp.js"></script>
    <link rel="stylesheet" crossorigin href="/monitoring-system/assets/index-tT0yvqSE.css">
  </head>
  <body>
    <div id="app" class="container-fluid"></div>
  </body>
</html>
